{
  "hash": "c64339865cd58173b0612b4a267b059a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Daisy Yuan\"\ndate: today\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n#| echo: false\n#| message: false\n#| results: hide\n\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\n\ncensus_api_key(Sys.getenv(\"CENSUS_API_KEY\"))\n\n# Load spatial data\npa_counties <- st_read(here(\"data/Pennsylvania_County_Boundaries.shp\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Pennsylvania_County_Boundaries' from data source \n  `C:\\Users\\10133\\Desktop\\UPENN\\MUSA5080_PPA\\Portfolio\\data\\Pennsylvania_County_Boundaries.shp' \n  using driver `ESRI Shapefile'\nSimple feature collection with 67 features and 19 fields\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: -8963377 ymin: 4825316 xmax: -8314404 ymax: 5201413\nProjected CRS: WGS 84 / Pseudo-Mercator\n```\n\n\n:::\n\n```{.r .cell-code}\nhospitals <- st_read(here(\"data/hospitals.geojson\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `hospitals' from data source \n  `C:\\Users\\10133\\Desktop\\UPENN\\MUSA5080_PPA\\Portfolio\\data\\hospitals.geojson' \n  using driver `GeoJSON'\nSimple feature collection with 223 features and 11 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: -80.49621 ymin: 39.75163 xmax: -74.86704 ymax: 42.13403\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n\n```{.r .cell-code}\n# Standardize CRS\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\n```\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\nThere are 223 hospitals in my dataset.\n\n- How many census tracts?\nThere are 3445 census tracts in my dataset.\n\n- What coordinate reference system is each dataset in?\nAll of them is now in WGS 1984\n\n\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n2022 5-year ACS data\n- How many tracts have missing income data?\n62\n- What is the median income across all PA census tracts?\n70188\n\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\nI chose the 25th percentile of median household income across PA tracts — meaning that tracts with income in the bottom quarter of the state are flagged\n\n- What elderly population threshold did you choose and why?\nI chose the 75th percentile of elderly share across PA tracts — meaning that tracts where the proportion of 65+ residents falls in the top quarter of the state are flagged.\n\n- How many tracts meet your vulnerability criteria?\n165 out of 3,383 valid PA census tracts meet the vulnerability criteria.\n\n- What percentage of PA census tracts are considered vulnerable by your definition?\nApproximately 4.9% of valid PA census tracts are considered vulnerable by this definition.\n\n\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.745881\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.15872\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\nOn average, vulnerable tracts are 4.75 miles from the nearest hospital.\n\n- What is the maximum distance?\nThe maximum distance to the nearest hospital among vulnerable tracts is 19.16 miles.\n\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\nNINE vulnerable tracts are more than 15 miles from the nearest hospital.\n\n\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.454545\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\nNine.\n\n- What percentage of vulnerable tracts are underserved?\nApproximately 5.5% vulnerable tracts are defined as underserved.\n\n- Does this surprise you? Why or why not?\nThis is not entirely surprising. Pennsylvania has a relatively dense hospital network, particularly in urban areas like Philadelphia and Pittsburgh, which keeps most tracts within reasonable distance. At 5.5%, the underserved share is reasonably small — but the 9 tracts that do exceed 15 miles are concerning, as low-income elderly residents in these areas are least likely to have reliable transportation to bridge that gap.\n\n\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\nvulnerable_tracts <- st_transform(vulnerable_tracts, st_crs(pa_counties))\nvulnerable_with_county <- vulnerable_tracts %>%\n  st_join(pa_counties %>% select(COUNTY_NAM))\n\n# Aggregate statistics by county\ncounty_stats <- vulnerable_with_county %>%\n  st_drop_geometry() %>%\n  group_by(COUNTY_NAM) %>%\n  summarise(\n    n_vulnerable = n(),\n    n_underserved = sum(underserved, na.rm = TRUE),\n    pct_underserved = (n_underserved / n_vulnerable) * 100,\n    avg_dist = mean(nearest_hosp_dist, na.rm = TRUE),\n    total_vulnerable_pop = sum(pop_65_plus, na.rm = TRUE)\n  ) %>%\n  arrange(desc(n_vulnerable))\n\n# Top 5 counties by percentage underserved\ncounty_stats %>%\n  arrange(desc(pct_underserved)) %>%\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  COUNTY_NAM n_vulnerable n_underserved pct_underserved avg_dist\n  <chr>             <int>         <int>           <dbl>    <dbl>\n1 PERRY                 2             2             100     17.5\n2 BRADFORD              1             1             100     16.7\n3 COLUMBIA              1             1             100     16.9\n4 JUNIATA               1             1             100     15.9\n5 MONROE                1             1             100     17.7\n# ℹ 1 more variable: total_vulnerable_pop <dbl>\n```\n\n\n:::\n\n```{.r .cell-code}\n# Counties with most vulnerable people far from hospitals\ncounty_stats %>%\n  filter(n_underserved > 0) %>%\n  arrange(desc(total_vulnerable_pop)) %>%\n  head(5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 6\n  COUNTY_NAM     n_vulnerable n_underserved pct_underserved avg_dist\n  <chr>                 <int>         <int>           <dbl>    <dbl>\n1 LUZERNE                   8             1            12.5     5.03\n2 WARREN                    7             1            14.3     6.87\n3 CRAWFORD                  6             1            16.7     8.36\n4 CLEARFIELD                5             1            20      10.1 \n5 NORTHUMBERLAND            5             1            20      12.8 \n# ℹ 1 more variable: total_vulnerable_pop <dbl>\n```\n\n\n:::\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\nPerry, Bradford, Columbia, Juniata, and Monroe all have 100% of their vulnerable tracts classified as underserved, with average distances ranging from 15.9 to 17.7 miles from the nearest hospital.\n\n- Which counties have the most vulnerable people living far from hospitals?\nLuzerne leads with 6,125 vulnerable elderly residents and 1 underserved tract, followed by Warren (5,963), Crawford (4,683), Clearfield (4,368), and Northumberland (3,395).\n\n- Are there any patterns in where underserved counties are located?\nThe underserved counties are predominantly rural, located in central and northern Pennsylvania (Perry, Juniata, Columbia, Bradford, Clearfield, Warren, Crawford). This aligns with the broader pattern of rural healthcare deserts, where low population density makes hospital infrastructure harder to sustain. \n\n\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nlibrary(knitr)\nlibrary(kableExtra)\n\ncounty_stats %>%\n  arrange(desc(pct_underserved), desc(total_vulnerable_pop)) %>%\n  head(10) %>%\n  mutate(\n    avg_dist = round(avg_dist, 2),\n    pct_underserved = round(pct_underserved, 1),\n    total_vulnerable_pop = comma(total_vulnerable_pop)\n  ) %>%\n  rename(\n    \"County\" = COUNTY_NAM,\n    \"Vulnerable Tracts\" = n_vulnerable,\n    \"Underserved Tracts\" = n_underserved,\n    \"% Underserved\" = pct_underserved,\n    \"Avg. Distance to Hospital (miles)\" = avg_dist,\n    \"Total Vulnerable Population\" = total_vulnerable_pop\n  ) %>%\n  kable(\n    caption = \"Top 10 Priority Counties for Healthcare Investment in Pennsylvania: Counties with the highest share of vulnerable tracts lacking adequate hospital access\",\n    align = c(\"l\", \"c\", \"c\", \"c\", \"c\", \"c\")\n  ) %>%\n  kable_styling(\n    bootstrap_options = c(\"striped\", \"hover\", \"condensed\"),\n    full_width = FALSE\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover table-condensed\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Top 10 Priority Counties for Healthcare Investment in Pennsylvania: Counties with the highest share of vulnerable tracts lacking adequate hospital access</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> County </th>\n   <th style=\"text-align:center;\"> Vulnerable Tracts </th>\n   <th style=\"text-align:center;\"> Underserved Tracts </th>\n   <th style=\"text-align:center;\"> % Underserved </th>\n   <th style=\"text-align:center;\"> Avg. Distance to Hospital (miles) </th>\n   <th style=\"text-align:center;\"> Total Vulnerable Population </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> PERRY </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 100 </td>\n   <td style=\"text-align:center;\"> 17.53 </td>\n   <td style=\"text-align:center;\"> 1,558 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BRADFORD </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 100 </td>\n   <td style=\"text-align:center;\"> 16.66 </td>\n   <td style=\"text-align:center;\"> 1,545 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> JUNIATA </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 100 </td>\n   <td style=\"text-align:center;\"> 15.91 </td>\n   <td style=\"text-align:center;\"> 492 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MONROE </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 100 </td>\n   <td style=\"text-align:center;\"> 17.68 </td>\n   <td style=\"text-align:center;\"> 314 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> COLUMBIA </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 100 </td>\n   <td style=\"text-align:center;\"> 16.91 </td>\n   <td style=\"text-align:center;\"> 282 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SULLIVAN </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 100 </td>\n   <td style=\"text-align:center;\"> 16.91 </td>\n   <td style=\"text-align:center;\"> 282 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> DAUPHIN </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 50 </td>\n   <td style=\"text-align:center;\"> 9.95 </td>\n   <td style=\"text-align:center;\"> 2,122 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TIOGA </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 50 </td>\n   <td style=\"text-align:center;\"> 8.65 </td>\n   <td style=\"text-align:center;\"> 1,416 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CLINTON </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 50 </td>\n   <td style=\"text-align:center;\"> 11.03 </td>\n   <td style=\"text-align:center;\"> 1,402 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FOREST </td>\n   <td style=\"text-align:center;\"> 2 </td>\n   <td style=\"text-align:center;\"> 1 </td>\n   <td style=\"text-align:center;\"> 50 </td>\n   <td style=\"text-align:center;\"> 15.25 </td>\n   <td style=\"text-align:center;\"> 1,311 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\nhospitals <- st_transform(hospitals, st_crs(pa_counties))\n\n# Join county_stats to pa_counties spatial data\ncounty_map <- pa_counties %>%\n  left_join(county_stats, by = \"COUNTY_NAM\")\n\n# Create county-level access map\nggplot() +\n  geom_sf(data = county_map,\n          aes(fill = pct_underserved),\n          color = \"white\", linewidth = 0.3) +\n  geom_sf(data = hospitals,\n          color = \"red\", size = 0.8, alpha = 0.6) +\n  scale_fill_distiller(\n    palette = \"YlOrRd\",\n    direction = 1,\n    na.value = \"gray90\",\n    name = \"% Underserved\\nVulnerable Tracts\",\n    labels = scales::label_percent(scale = 1)\n  ) +\n  labs(\n    title = \"County-Level Hospital Access for Vulnerable Populations in Pennsylvania\",\n    subtitle = \"Share of vulnerable tracts more than 15 miles from the nearest hospital\",\n    caption = \"Source: U.S. Census Bureau ACS 2022, PA County Boundaries\\nVulnerable tracts defined as low-income (bottom 25%) with high elderly share (top 25%)\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\nggplot() +\n  geom_sf(data = pa_counties, \n          fill = \"gray95\", color = \"gray60\", linewidth = 0.3) +\n  geom_sf(data = vulnerable_tracts %>% filter(!underserved),\n          fill = \"lightyellow\", color = NA, alpha = 0.7) +\n  geom_sf(data = vulnerable_tracts %>% filter(underserved),\n          fill = \"red\", color = NA, alpha = 0.9) +\n  geom_sf(data = hospitals,\n          color = \"blue\", size = 0.8, alpha = 0.6) +\n  labs(\n    title = \"Underserved Vulnerable Tracts in Pennsylvania\",\n    subtitle = \"Red tracts are low-income, elderly, and more than 15 miles from the nearest hospital\",\n    caption = \"Source: U.S. Census Bureau ACS 2022\\nBlue points = Hospitals\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\n\n# Plot 1: Histogram weighted by elderly population\np1 <- ggplot(vulnerable_tracts, aes(x = nearest_hosp_dist, weight = pop_65_plus)) +\n  geom_histogram(aes(fill = after_stat(x) > 15), bins = 30, alpha = 0.8) +\n  scale_fill_manual(\n    values = c(\"FALSE\" = \"steelblue\", \"TRUE\" = \"red\"),\n    labels = c(\"FALSE\" = \"Served\", \"TRUE\" = \"Underserved\"),\n    name = \"\"\n  ) +\n  labs(\n    title = \"Elderly Population by Distance to Nearest Hospital\",\n    subtitle = \"Among vulnerable tracts in Pennsylvania\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    y = \"Total Elderly Population (65+)\",\n    caption = \"Red bars = beyond 15-mile underserved threshold\"\n  ) +\n  theme_minimal()\n\n# Plot 2: Scatter plot of distance vs elderly population\np2 <- ggplot(vulnerable_tracts, aes(x = nearest_hosp_dist, y = pop_65_plus, color = underserved)) +\n  geom_point(alpha = 0.7) +\n  scale_color_manual(\n    values = c(\"FALSE\" = \"steelblue\", \"TRUE\" = \"red\"),\n    labels = c(\"FALSE\" = \"Served\", \"TRUE\" = \"Underserved\"),\n    name = \"\"\n  ) +\n  labs(\n    title = \"Elderly Population vs. Distance to Nearest Hospital by Tract\",\n    subtitle = \"Among vulnerable tracts in Pennsylvania\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    y = \"Total Elderly Population (65+)\",\n    caption = \"Source: U.S. Census Bureau ACS 2022\"\n  ) +\n  theme_minimal()\n\n# Comparison\np1 / p2\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\n#The histogram shows the total elderly population living in the census tracts at certain distance range from the nearest hospital. \n#The majority of bars are concentrated within 5 miles and decline sharply beyond that\n#The dashline marks the threshold of underserved population.\n```\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\n\n\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n\n**School Safety Zones**\n- **Data:** Schools, Crime Incidents, Collision\n- **Question:** \"Are school zones safe for commuting, or are they danger hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents and collision count\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n:::\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\nI chose three datasets from OpenDataPhilly: Philadelphia crime incidents (2020–2024 aggregate), traffic collision data (2020–2024), and school parcels. Crime and collision data were chosen because both directly affect student safety around schools. Violent crime threatens personal safety while traffic collisions are a major concern for students walking or biking to school.\n\n- What is the data source and date?\nAll datasets are from OpenDataPhilly, maintained by the City of Philadelphia. Crime and collision data span 2020–2024 and school parcels reflect current school locations.\n\n- How many features does it contain?\nAfter filtering for relevant crime categories, the crime dataset contains 234,858 incidents across five years. The collision dataset contains 36,303 records over the same period.\n\n- What CRS is it in? Did you need to transform it?\nAll datasets are in EPSG 3857 (WGS 84 / Pseudo-Mercator), the same CRS as \"pa_counties\". No additional transformation was needed since they already matched.\n\n\n2. **Pose a research question**\n\nAre school safety zones in Philadelphia's high-violation tracts disproportionately exposed to crime incidents and traffic hazards?\n\n**Examples:**\n- \"Do vulnerable tracts have adequate public transit access to hospitals?\"\n- \"Are EMS stations appropriately located near vulnerable populations?\"\n- \"Do areas with low vehicle access have worse hospital access?\"\n\n\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n## buffer school safety zone and calculate number of crime and collision for each school\n# 1000ft = 304.8 meters in EPSG 3857\nsafety_zone <- schools %>%\n  st_buffer(dist = 304.8)\n\n# Spatial join\ncrime_in_buffer <- safety_zone %>%\n  st_join(crime) %>%\n  st_drop_geometry() %>%\n  group_by(objectid.x) %>%\n  summarise(crime_count = n()) %>%\n  rename(objectid = objectid.x)\n\ncollision_in_buffer <- safety_zone %>%\n  st_join(collision) %>%\n  st_drop_geometry() %>%\n  group_by(objectid.x) %>%\n  summarise(collision_count = n()) %>%\n  rename(objectid = objectid.x)\n\n# Join counts\nsafety_zone <- schools %>%\n  st_buffer(dist = 304.8) %>%\n  left_join(crime_in_buffer, by = \"objectid\") %>%\n  left_join(collision_in_buffer, by = \"objectid\") %>%\n  mutate(\n    crime_count = replace_na(crime_count, 0),\n    collision_count = replace_na(collision_count, 0),\n    danger_score = crime_count + collision_count\n  )\n\n##identify the top 5 dangerous school parcels by crime/collision/crime + collision (= danger)/\n##top 20% crime and top 20% collision\n\n# Flag high-violation schools (top 20% in BOTH crime and collision)\ncrime_cut <- quantile(safety_zone$crime_count, 0.80, na.rm = TRUE)\ncollision_cut <- quantile(safety_zone$collision_count, 0.80, na.rm = TRUE)\n\nsafety_zone <- safety_zone %>%\n  mutate(high_violation = crime_count >= crime_cut & collision_count >= collision_cut)\nsum(safety_zone$high_violation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 52\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = schools, fill = \"gray90\", color = \"gray60\", linewidth = 0.3) +\n  geom_sf(data = safety_zone %>% filter(high_violation),\n          fill = \"red\", alpha = 0.6, color = \"darkred\", linewidth = 0.3) +\n  labs(\n    title = \"High-Violation School Safety Zones in Philadelphia\",\n    subtitle = \"Schools in top 20% of both crime and collision counts\",\n    caption = \"Source: OpenDataPhilly 2020-2024\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# top 5 dangerous school parcels\ntop5_crime <- safety_zone %>%\n  st_drop_geometry() %>%\n  arrange(desc(crime_count)) %>%\n  head(5) %>%\n  select(objectid, school_nam, crime_count, collision_count, danger_score) %>%\n  kable(caption = \"Top 5 Schools by Crime Count\",\n        col.names = c(\"ID\", \"School Name\", \"Crime Count\", \"Collision Count\", \"Danger Score\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"), full_width = FALSE)\n\ntop5_collision <- safety_zone %>%\n  st_drop_geometry() %>%\n  arrange(desc(collision_count)) %>%\n  head(5) %>%\n  select(objectid, school_nam, crime_count, collision_count, danger_score) %>%\n  kable(caption = \"Top 5 Schools by Collision Count\",\n        col.names = c(\"ID\", \"School Name\", \"Crime Count\", \"Collision Count\", \"Danger Score\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"), full_width = FALSE)\n\ntop5_danger <- safety_zone %>%\n  st_drop_geometry() %>%\n  arrange(desc(danger_score)) %>%\n  head(5) %>%\n  select(objectid, school_nam, crime_count, collision_count, danger_score) %>%\n  kable(caption = \"Top 5 Schools by Combined Danger Score\",\n        col.names = c(\"ID\", \"School Name\", \"Crime Count\", \"Collision Count\", \"Danger Score\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"), full_width = FALSE)\n\ntop5_crime\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Top 5 Schools by Crime Count</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> ID </th>\n   <th style=\"text-align:left;\"> School Name </th>\n   <th style=\"text-align:right;\"> Crime Count </th>\n   <th style=\"text-align:right;\"> Collision Count </th>\n   <th style=\"text-align:right;\"> Danger Score </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 86 </td>\n   <td style=\"text-align:left;\"> CONWELL, RUSSELL MIDDLE SCHOOL </td>\n   <td style=\"text-align:right;\"> 2053 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 2099 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 315 </td>\n   <td style=\"text-align:left;\"> WILLARD, FRANCES E. SCHOOL </td>\n   <td style=\"text-align:right;\"> 1400 </td>\n   <td style=\"text-align:right;\"> 44 </td>\n   <td style=\"text-align:right;\"> 1444 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 222 </td>\n   <td style=\"text-align:left;\"> FREIRE CHARTER SCHOOL </td>\n   <td style=\"text-align:right;\"> 1159 </td>\n   <td style=\"text-align:right;\"> 60 </td>\n   <td style=\"text-align:right;\"> 1219 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 464 </td>\n   <td style=\"text-align:left;\"> K012 KIDS SCHOOL </td>\n   <td style=\"text-align:right;\"> 1126 </td>\n   <td style=\"text-align:right;\"> 68 </td>\n   <td style=\"text-align:right;\"> 1194 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 70 </td>\n   <td style=\"text-align:left;\"> VISITATION SCHOOL </td>\n   <td style=\"text-align:right;\"> 912 </td>\n   <td style=\"text-align:right;\"> 74 </td>\n   <td style=\"text-align:right;\"> 986 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\ntop5_collision\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Top 5 Schools by Collision Count</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> ID </th>\n   <th style=\"text-align:left;\"> School Name </th>\n   <th style=\"text-align:right;\"> Crime Count </th>\n   <th style=\"text-align:right;\"> Collision Count </th>\n   <th style=\"text-align:right;\"> Danger Score </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 119 </td>\n   <td style=\"text-align:left;\"> DUCKREY, TANNER SCHOOL </td>\n   <td style=\"text-align:right;\"> 566 </td>\n   <td style=\"text-align:right;\"> 150 </td>\n   <td style=\"text-align:right;\"> 716 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 137 </td>\n   <td style=\"text-align:left;\"> ROMAN CATHOLIC HIGH SCHOOL </td>\n   <td style=\"text-align:right;\"> 330 </td>\n   <td style=\"text-align:right;\"> 141 </td>\n   <td style=\"text-align:right;\"> 471 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 331 </td>\n   <td style=\"text-align:left;\"> KENDERTON ELEMENTARY </td>\n   <td style=\"text-align:right;\"> 380 </td>\n   <td style=\"text-align:right;\"> 133 </td>\n   <td style=\"text-align:right;\"> 513 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 313 </td>\n   <td style=\"text-align:left;\"> YOUTHBUILD PHILADELPHIA CHARTER </td>\n   <td style=\"text-align:right;\"> 659 </td>\n   <td style=\"text-align:right;\"> 123 </td>\n   <td style=\"text-align:right;\"> 782 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 452 </td>\n   <td style=\"text-align:left;\"> TECH FREIRE CHARTER SCHOOL </td>\n   <td style=\"text-align:right;\"> 618 </td>\n   <td style=\"text-align:right;\"> 123 </td>\n   <td style=\"text-align:right;\"> 741 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\ntop5_danger\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Top 5 Schools by Combined Danger Score</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> ID </th>\n   <th style=\"text-align:left;\"> School Name </th>\n   <th style=\"text-align:right;\"> Crime Count </th>\n   <th style=\"text-align:right;\"> Collision Count </th>\n   <th style=\"text-align:right;\"> Danger Score </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 86 </td>\n   <td style=\"text-align:left;\"> CONWELL, RUSSELL MIDDLE SCHOOL </td>\n   <td style=\"text-align:right;\"> 2053 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 2099 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 315 </td>\n   <td style=\"text-align:left;\"> WILLARD, FRANCES E. SCHOOL </td>\n   <td style=\"text-align:right;\"> 1400 </td>\n   <td style=\"text-align:right;\"> 44 </td>\n   <td style=\"text-align:right;\"> 1444 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 222 </td>\n   <td style=\"text-align:left;\"> FREIRE CHARTER SCHOOL </td>\n   <td style=\"text-align:right;\"> 1159 </td>\n   <td style=\"text-align:right;\"> 60 </td>\n   <td style=\"text-align:right;\"> 1219 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 464 </td>\n   <td style=\"text-align:left;\"> K012 KIDS SCHOOL </td>\n   <td style=\"text-align:right;\"> 1126 </td>\n   <td style=\"text-align:right;\"> 68 </td>\n   <td style=\"text-align:right;\"> 1194 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 70 </td>\n   <td style=\"text-align:left;\"> VISITATION SCHOOL </td>\n   <td style=\"text-align:right;\"> 912 </td>\n   <td style=\"text-align:right;\"> 74 </td>\n   <td style=\"text-align:right;\"> 986 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##calculate the average distance from danger point in a school buffer to the school\nschools <- rename(schools, OBJECTID = objectid)\n\n# Crime distances\ncrime_dist_matrix <- st_distance(crime, schools)\n\ncrime_dist <- crime %>%\n  mutate(dist_to_school = apply(crime_dist_matrix, 1, min)) %>%\n  st_join(safety_zone %>% select(objectid)) %>%\n  st_drop_geometry() %>%\n  group_by(objectid.y) %>%\n  summarise(avg_crime_dist = mean(dist_to_school, na.rm = TRUE)) %>%\n  rename(objectid = objectid.y)\n\nsafety_zone <- safety_zone %>%\n  left_join(crime_dist, by = \"objectid\")\n\n# Collision distances\ncollision_dist_matrix <- st_distance(collision, schools)\n\ncollision_dist <- collision %>%\n  mutate(dist_to_school = apply(collision_dist_matrix, 1, min)) %>%\n  st_join(safety_zone %>% select(objectid)) %>%\n  st_drop_geometry() %>%\n  group_by(objectid.y) %>%\n  summarise(avg_collision_dist = mean(dist_to_school, na.rm = TRUE)) %>%\n  rename(objectid = objectid.y)\n\nsafety_zone <- safety_zone %>%\n  left_join(collision_dist, by = \"objectid\")\n\n# Top 5 by average crime distance\ntop5_crime_dist <- safety_zone %>%\n  st_drop_geometry() %>%\n  arrange(avg_crime_dist) %>%\n  head(5) %>%\n  select(objectid, school_nam, avg_crime_dist) %>%\n  kable(caption = \"Top 5 Schools with Least Average Crime Distance (meters)\",\n        col.names = c(\"ID\", \"School Name\", \"Avg Crime Distance (m)\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"), full_width = FALSE)\n\n# Top 5 by average collision distance\ntop5_collision_dist <- safety_zone %>%\n  st_drop_geometry() %>%\n  arrange(avg_collision_dist) %>%\n  head(5) %>%\n  select(objectid, school_nam, avg_collision_dist) %>%\n  kable(caption = \"Top 5 Schools by Average Collision Distance (meters)\",\n        col.names = c(\"ID\", \"School Name\", \"Avg Collision Distance (m)\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"), full_width = FALSE)\n\ntop5_crime_dist\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Top 5 Schools with Least Average Crime Distance (meters)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> ID </th>\n   <th style=\"text-align:left;\"> School Name </th>\n   <th style=\"text-align:right;\"> Avg Crime Distance (m) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 73 </td>\n   <td style=\"text-align:left;\"> NAZARETH ACADEMY HIGH SCHOOL </td>\n   <td style=\"text-align:right;\"> 39.56615 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 384 </td>\n   <td style=\"text-align:left;\"> MATH, SCIENCE AND TECHNOLOGY </td>\n   <td style=\"text-align:right;\"> 55.24363 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 473 </td>\n   <td style=\"text-align:left;\"> NA </td>\n   <td style=\"text-align:right;\"> 100.19317 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 304 </td>\n   <td style=\"text-align:left;\"> ROXBOROUGH HIGH SCHOOL </td>\n   <td style=\"text-align:right;\"> 100.85450 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 130 </td>\n   <td style=\"text-align:left;\"> FELTONVILLE ARTS &amp; SCIENCES </td>\n   <td style=\"text-align:right;\"> 114.11754 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\ntop5_collision_dist\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>Top 5 Schools by Average Collision Distance (meters)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> ID </th>\n   <th style=\"text-align:left;\"> School Name </th>\n   <th style=\"text-align:right;\"> Avg Collision Distance (m) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 186 </td>\n   <td style=\"text-align:left;\"> MIFFLIN, THOMAS SCHOOL </td>\n   <td style=\"text-align:right;\"> 95.84298 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 153 </td>\n   <td style=\"text-align:left;\"> PENNSYLVANIA SCHOOL FOR THE DEAF </td>\n   <td style=\"text-align:right;\"> 104.24374 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 173 </td>\n   <td style=\"text-align:left;\"> CARNELL, LAURA H. SCHOOL </td>\n   <td style=\"text-align:right;\"> 110.58027 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 467 </td>\n   <td style=\"text-align:left;\"> SAINTS TABERNACLE DAY SCHOOL </td>\n   <td style=\"text-align:right;\"> 114.22460 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 254 </td>\n   <td style=\"text-align:left;\"> MASTERY CHARTER @ PICKETT </td>\n   <td style=\"text-align:right;\"> 116.87737 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n\n```{.r .cell-code}\n# Flag schools with least 20% crime distance and least 20% collision distance\ncrime_dist_cut <- quantile(safety_zone$avg_crime_dist, 0.20, na.rm = TRUE)\ncollision_dist_cut <- quantile(safety_zone$avg_collision_dist, 0.20, na.rm = TRUE)\n\nsafety_zone <- safety_zone %>%\n  mutate(high_violation_dist = avg_crime_dist <= crime_dist_cut & avg_collision_dist <= collision_dist_cut)\ncat(\"Number of high-violation distance schools:\", sum(safety_zone$high_violation_dist, na.rm = TRUE), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of high-violation distance schools: 46 \n```\n\n\n:::\n\n```{.r .cell-code}\n##aggregate by census tract and county\n# Step 5: Aggregate by census tract and county\n# First transform census_tracts to match CRS\npa_tract <- st_transform(pa_tract, st_crs(safety_zone))\n\n# Spatial join safety_zone to census tracts\nsafety_zone_tracts <- safety_zone %>%\n  st_join(pa_tract %>% select(GEOID, NAME)) %>%\n  st_drop_geometry() %>%\n  group_by(GEOID, NAME) %>%\n  summarise(\n    n_schools = n(),\n    n_high_violation = sum(high_violation, na.rm = TRUE),\n    n_high_violation_dist = sum(high_violation_dist, na.rm = TRUE),\n    avg_crime_count = mean(crime_count, na.rm = TRUE),\n    avg_collision_count = mean(collision_count, na.rm = TRUE),\n    avg_crime_dist = mean(avg_crime_dist, na.rm = TRUE),\n    avg_collision_dist = mean(avg_collision_dist, na.rm = TRUE)\n  ) %>%\n  mutate(\n    high_violation_rate = n_high_violation / n_schools * 100,\n    high_violation_dist_rate = n_high_violation_dist / n_schools * 100,\n    tract_num = str_extract(NAME, \"(?<=Census Tract )\\\\d+\\\\.?\\\\d*\")\n  ) %>%\n  arrange(desc(n_high_violation))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##visualization\n# Visualization 1: Tract-level choropleth map\ntract_map <- pa_tract %>%\n  left_join(safety_zone_tracts %>% st_drop_geometry(), by = \"GEOID\") %>%\n  filter(!is.na(high_violation_rate))\n\nggplot() +\n  geom_sf(data = pa_counties %>% filter(COUNTY_NAM == \"PHILADELPHIA\"),\n          fill = \"gray95\", color = \"gray60\", linewidth = 0.3) +\n  geom_sf(data = tract_map,\n          aes(fill = high_violation_rate),\n          color = \"white\", linewidth = 0.2) +\n  scale_fill_distiller(\n    palette = \"YlOrRd\",\n    direction = 1,\n    na.value = \"gray90\",\n    name = \"% High Violation\\nSchools\",\n    labels = scales::label_percent(scale = 1)\n  ) +\n  labs(\n    title = \"High-Violation School Safety Zones by Census Tract\",\n    subtitle = \"Share of schools in top 20% of both crime and collision counts\",\n    caption = \"Source: OpenDataPhilly 2020-2024\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Visualization 2: Compare high_violation vs high_violation_dist\nggplot() +\n  geom_sf(data = pa_counties %>% filter(COUNTY_NAM == \"PHILADELPHIA\"),\n          fill = \"gray95\", color = \"gray60\", linewidth = 0.3) +\n  geom_sf(data = safety_zone,\n          fill = \"gray80\", color = NA, alpha = 0.5) +\n  geom_sf(data = safety_zone %>% filter(high_violation),\n          fill = \"orange\", color = NA, alpha = 0.7) +\n  geom_sf(data = safety_zone %>% filter(high_violation_dist),\n          fill = \"red\", color = NA, alpha = 0.7) +\n  labs(\n    title = \"High-Violation School Safety Zones in Philadelphia\",\n    subtitle = \"Orange = high crime/collision count | Red = close crime/collision violations\",\n    caption = \"Source: OpenDataPhilly 2020-2024\"\n  ) +\n  theme_void()\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-14-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Visualization 3: Crime and Collision Distribution Across Philadelphia School Safety Zones\np3 <- ggplot(safety_zone, aes(x = crime_count, fill = high_violation)) +\n  geom_histogram(bins = 30, alpha = 0.8) +\n  scale_fill_manual(\n    values = c(\"FALSE\" = \"steelblue\", \"TRUE\" = \"red\"),\n    labels = c(\"FALSE\" = \"Normal\", \"TRUE\" = \"High Violation\"),\n    name = \"\"\n  ) +\n  labs(\n    title = \"Distribution of Crime Counts Across School Safety Zones\",\n    x = \"Crime Count (2020-2024)\",\n    y = \"Number of Schools\",\n    caption = \"Red = top 20% in both crime and collision counts\"\n  ) +\n  theme_minimal()\n\n# p2: Scatter plot of crime_count vs collision_count colored by high_violation\np4 <- ggplot(safety_zone, aes(x = crime_count, y = collision_count, color = high_violation)) +\n  geom_point(alpha = 0.7) +\n  scale_color_manual(\n    values = c(\"FALSE\" = \"steelblue\", \"TRUE\" = \"red\"),\n    labels = c(\"FALSE\" = \"Normal\", \"TRUE\" = \"High Violation\"),\n    name = \"\"\n  ) +\n  labs(\n    title = \"Crime Count vs. Collision Count by School\",\n    x = \"Crime Count (2020-2024)\",\n    y = \"Collision Count (2020-2024)\",\n    caption = \"Source: OpenDataPhilly 2020-2024\"\n  ) +\n  theme_minimal()\n\np3 / p4\n```\n\n::: {.cell-output-display}\n![](lab2_template_files/figure-html/unnamed-chunk-14-3.png){width=672}\n:::\n:::\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\nThis analysis examined 490 school safety zones across Philadelphia using crime incident and traffic collision data from 2020 to 2024. Of the 490 schools, 52 (10.6%) were classified as high-violation by count — falling in the top 20% of both crime and collision counts — while 46 schools (9.4%) were flagged as high-violation by distance, meaning violations tend to cluster very close to the school itself. The histogram shows that most schools have fewer than 500 crime incidents over the five-year period, with high-violation schools appearing at the higher end of the distribution, confirming that the top 20% threshold effectively separates genuinely dangerous zones from the rest. The scatter plot further reveals a positive relationship between crime count and collision count — schools with more crime also tend to have more collisions — and high-violation schools cluster distinctly in the upper right, indicating that danger tends to be compounded rather than isolated to a single incident type. At the census tract level, dangerous school zones are mostly concentrated in tracts along North Broad Street, Kensington, and West Philadelphia, underscoring the need for targeted Safe Routes to School investments in these specific corridors where students face both high volumes of crime and violations occurring in close proximity to school grounds.\n\n\n## Finally - A few comments about your incorporation of feedback!\nI try to avoid unnecessary code like print() and head(). Besides, I used \"#| echo: false, #| message: false, and #| results: hide\" to hide setup code. \n\n\n\n## Submission Requirements\n\n**What to submit:**\n\n1. **Rendered HTML document posted to your course portfolio** with all code, outputs, maps, and text\n   - Use `embed-resources: true` in YAML so it's a single file\n   - All code should run without errors\n   - All maps and charts should display correctly\n2. Submit the correct and working links of your assignment on Canvas\n",
    "supporting": [
      "lab2_template_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}